#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Zagros Node installer — this is the command the panel's
# "Generate installer command" button produces.
#
#   curl -fsSL https://raw.githubusercontent.com/ZagrosGM/zagros-scripts/main/install-node.sh \
#     | bash -s -- --panel-id panel-xxxx --token <ONE-TIME-TOKEN> \
#              --name de-1 --address 203.0.113.10 --port 62050 --api-port 62051
#
# It lives in zagros-scripts, next to the panel's own installer, because
# installing anything Zagros should mean fetching from one place — the agent
# repository (zagros-node) builds the image and nothing else.
#
# What it does, and nothing else:
#   1. installs Docker (only if missing) and the compose plugin;
#   2. writes /opt/zagros-node/{.env,docker-compose.yml};
#   3. installs the `zagros-node` host CLI (from this same repository);
#   4. pulls the image (or builds it locally with --local-build);
#   5. starts the node and prints the pairing material you paste into the
#      panel: the node id and the TLS certificate SHA-256 fingerprint.
#
# It is idempotent: re-running it repairs/updates an existing install. The
# one-time token is never written to disk — only its SHA-256 is.
#
# Environment overrides:
#   ZAGROS_SCRIPTS_REF   git ref (branch/tag/sha) of zagros-scripts to use
# ---------------------------------------------------------------------------
set -euo pipefail

REPO_RAW="${ZAGROS_NODE_REPO_RAW:-https://raw.githubusercontent.com/ZagrosGM/zagros-scripts}"
REF="${ZAGROS_SCRIPTS_REF:-${ZAGROS_NODE_SCRIPTS_REF:-main}}"
INSTALL_DIR="${ZAGROS_NODE_DIR:-/opt/zagros-node}"
DATA_DIR="${ZAGROS_NODE_HOST_DATA:-/var/lib/zagros}"
IMAGE="${ZAGROS_NODE_IMAGE:-ghcr.io/zagrosgm/zagros-node:latest}"
CLI_PATH="/usr/local/bin/zagros-node"

PANEL_ID=""
TOKEN=""
NODE_NAME=""
ADDRESS=""
PORT="62050"
API_PORT="62051"
LOCAL_BUILD=""
NO_START=0
SKIP_DOCKER=0

# --------------------------------------------------------------------------- #
# output helpers
# --------------------------------------------------------------------------- #
if [ -t 1 ] && [ -z "${NO_COLOR:-}" ]; then
  B=$'\033[1m'; D=$'\033[2m'; G=$'\033[32m'; Y=$'\033[33m'; R=$'\033[31m'; C=$'\033[36m'; N=$'\033[0m'
else
  B=""; D=""; G=""; Y=""; R=""; C=""; N=""
fi
step() { printf '\n%s==>%s %s%s%s\n' "$C" "$N" "$B" "$*" "$N"; }
info() { printf '    %s\n' "$*"; }
ok()   { printf '    %s✓%s %s\n' "$G" "$N" "$*"; }
warn() { printf '    %s!%s %s\n' "$Y" "$N" "$*" >&2; }
die()  { printf '\n%serror:%s %s\n' "$R" "$N" "$*" >&2; exit 1; }

usage() {
  cat <<'USAGE'
Usage: install-node.sh [options]

  --panel-id ID        panel identifier (generated by the panel)
  --token TOKEN        one-time registration token (generated by the panel)
  --name NAME          node name shown in the panel (default: hostname)
  --address ADDR       comma-separated IPs/DNS names the panel reaches this
                       node on (default: auto-detected primary address)
  --port PORT          control-plane HTTPS port        (default 62050)
  --api-port PORT      bootstrap/info port             (default 62051)
  --image REF          node image reference            (default ghcr.io/zagrosgm/zagros-node:latest)
  --data-dir PATH      host data directory             (default /var/lib/zagros)
  --local-build DIR    build the image from this source tree instead of pulling
                       (a zagros-node checkout)
  --skip-docker        do not install Docker (assume it is present)
  --no-start           install only; do not start the node
  -h | --help          this help
USAGE
}

while [ $# -gt 0 ]; do
  case "$1" in
    --panel-id)       PANEL_ID="${2:?--panel-id needs a value}"; shift 2 ;;
    --token)          TOKEN="${2:?--token needs a value}"; shift 2 ;;
    --name)           NODE_NAME="${2:?--name needs a value}"; shift 2 ;;
    --address)        ADDRESS="${2:?--address needs a value}"; shift 2 ;;
    --port)           PORT="${2:?--port needs a value}"; shift 2 ;;
    --api-port)       API_PORT="${2:?--api-port needs a value}"; shift 2 ;;
    --image)          IMAGE="${2:?--image needs a value}"; shift 2 ;;
    --data-dir)       DATA_DIR="${2:?--data-dir needs a value}"; shift 2 ;;
    --local-build)    LOCAL_BUILD="${2:?--local-build needs a directory}"; shift 2 ;;
    --skip-docker)    SKIP_DOCKER=1; shift ;;
    --no-start)       NO_START=1; shift ;;
    -h|--help)        usage; exit 0 ;;
    *)                die "unknown argument: $1 (try --help)" ;;
  esac
done

[ "$(id -u)" -eq 0 ] || die "run as root: curl -fsSL $REPO_RAW/$REF/install-node.sh | sudo bash -s -- ..."

# --------------------------------------------------------------------------- #
step "Checking the host"
# --------------------------------------------------------------------------- #
ARCH="$(uname -m)"
case "$ARCH" in
  x86_64|amd64) ARCH="amd64" ;;
  *) die "unsupported architecture '$ARCH' — the node image is amd64-only (accel-ppp/PPTP and the pinned PPP packages are)" ;;
esac
ok "architecture: $ARCH"

if [ -r /etc/os-release ]; then
  # shellcheck disable=SC1091
  . /etc/os-release
  info "operating system: ${PRETTY_NAME:-${ID:-unknown}}"
else
  warn "no /etc/os-release — continuing, but Docker installation may need to be done manually"
fi

if [ -z "$NODE_NAME" ]; then
  NODE_NAME="$(hostname 2>/dev/null || echo zagros-node)"
fi

if [ -z "$ADDRESS" ]; then
  ADDRESS="$(ip -4 route get 192.0.2.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src") print $(i+1); exit}' || true)"
  [ -n "$ADDRESS" ] && ok "detected primary address: $ADDRESS" \
                    || warn "could not detect the public address — pass --address explicitly (it must be a certificate SAN)"
fi

# --------------------------------------------------------------------------- #
step "Installing Docker"
# --------------------------------------------------------------------------- #
if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
  ok "docker already available: $(docker --version | head -1)"
else
  [ "$SKIP_DOCKER" -eq 0 ] || die "docker is not usable and --skip-docker was given"
  info "installing docker (get.docker.com)…"
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL https://get.docker.com | sh
  elif command -v wget >/dev/null 2>&1; then
    wget -qO- https://get.docker.com | sh
  else
    die "neither curl nor wget is available — install Docker manually"
  fi
  ok "docker installed"
fi

if ! docker compose version >/dev/null 2>&1; then
  info "installing the compose plugin…"
  if command -v apt-get >/dev/null 2>&1; then
    apt-get update -qq && apt-get install -y -qq docker-compose-plugin || \
      warn "could not install docker-compose-plugin automatically"
  else
    warn "docker compose plugin missing — install it for your distribution"
  fi
fi

if command -v systemctl >/dev/null 2>&1 && systemctl list-unit-files 2>/dev/null | grep -q docker; then
  systemctl enable --now docker >/dev/null 2>&1 || true
fi
docker info >/dev/null 2>&1 || die "docker daemon is not running (start it, then re-run this installer)"

# --------------------------------------------------------------------------- #
step "Writing configuration to $INSTALL_DIR"
# --------------------------------------------------------------------------- #
mkdir -p "$INSTALL_DIR" "$DATA_DIR"

TOKEN_HASH=""
if [ -n "$TOKEN" ]; then
  [ ${#TOKEN} -ge 16 ] || die "the registration token is too short (panel tokens are >= 16 chars)"
  TOKEN_HASH="$(printf '%s' "$TOKEN" | sha256sum | cut -d' ' -f1)"
fi

cat > "$INSTALL_DIR/.env" <<EOF
# Generated by install-node.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
# The one-time token itself is NOT stored here, only its SHA-256.
ZAGROS_NODE_NAME=$NODE_NAME
ZAGROS_NODE_ADDRESS=$ADDRESS
ZAGROS_NODE_HOST=0.0.0.0
ZAGROS_NODE_PORT=$PORT
ZAGROS_NODE_API_PORT=$API_PORT
ZAGROS_NODE_INFO_BIND=0.0.0.0
ZAGROS_NODE_INFO_DETAIL=0
ZAGROS_NODE_REGISTRATION_HASH=$TOKEN_HASH
ZAGROS_NODE_IMAGE=$IMAGE
ZAGROS_NODE_DATA=/var/lib/zagros/node
EOF
chmod 600 "$INSTALL_DIR/.env"
ok "wrote $INSTALL_DIR/.env (mode 0600)"

# --------------------------------------------------------------------------- #
step "Fetching the compose manifest and CLI"
# --------------------------------------------------------------------------- #
# The node's compose manifest is rendered here rather than downloaded: the
# agent repository ships the image, and an installer that can only run when a
# second repository happens to be reachable is an installer that fails at the
# worst moment.
cat > "$INSTALL_DIR/docker-compose.yml" <<'COMPOSE'
# Zagros Node — rendered by install-node.sh.
#
# network_mode: host is required, not a preference: the node binds the
# inbound ports its cores serve (443, 1194, 51820, 1723, ...), and those
# ports are only knowable at runtime. Port-mapping dozens of dynamic
# listeners through a bridge would be both fragile and lossy.
services:
  zagros-node:
    image: ${ZAGROS_NODE_IMAGE:-ghcr.io/zagrosgm/zagros-node:latest}
    container_name: zagros-node
    restart: always
    network_mode: host
    # TUN cores (OpenVPN, WireGuard) create interfaces: without NET_ADMIN and
    # the tunnel device their start dies at interface creation. NET_RAW is
    # required by the PPTP engine (GRE protocol 47), SYS_ADMIN by per-outbound
    # network namespaces. The node never receives the Docker socket.
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
      - /dev/ppp:/dev/ppp
    volumes:
      - /var/lib/zagros:/var/lib/zagros
    env_file:
      - .env
COMPOSE
ok "wrote $INSTALL_DIR/docker-compose.yml"

if [ -n "$LOCAL_BUILD" ] && [ -f "$LOCAL_BUILD/scripts/zagros-node" ]; then
  cp -f "$LOCAL_BUILD/scripts/zagros-node" "$CLI_PATH"
else
  curl -fsSL "$REPO_RAW/$REF/zagros-node" -o "$CLI_PATH" \
    || die "could not download the CLI from $REPO_RAW/$REF/zagros-node"
fi
chmod +x "$CLI_PATH"
ok "installed the CLI at $CLI_PATH"

# --------------------------------------------------------------------------- #
step "Obtaining the node image"
# --------------------------------------------------------------------------- #
if [ -n "$LOCAL_BUILD" ]; then
  info "building the image locally from $LOCAL_BUILD (this takes a few minutes)…"
  ( cd "$LOCAL_BUILD" && docker build -t "$IMAGE" . ) || die "local image build failed"
  ok "built $IMAGE"
else
  info "pulling $IMAGE …"
  docker pull "$IMAGE" || die "could not pull $IMAGE (check network/GHCR access)"
  ok "pulled $IMAGE"
fi

# --------------------------------------------------------------------------- #
if [ "$NO_START" -eq 1 ]; then
  step "Installed (--no-start)"
  info "start it with: zagros-node up"
  exit 0
fi

step "Starting the node"
# --------------------------------------------------------------------------- #
cd "$INSTALL_DIR"
if docker compose version >/dev/null 2>&1; then
  docker compose up -d --remove-orphans
else
  warn "docker compose is unavailable — starting with plain docker run"
  docker rm -f zagros-node >/dev/null 2>&1 || true
  docker run -d --name zagros-node --network host --restart always \
    --cap-add NET_ADMIN --cap-add NET_RAW --cap-add SYS_ADMIN \
    --device /dev/net/tun --device /dev/ppp \
    -v /var/lib/zagros:/var/lib/zagros \
    --env-file "$INSTALL_DIR/.env" "$IMAGE"
fi

printf '    waiting for the agent'
HEALTHY=0
for _ in $(seq 1 60); do
  if curl -fsS "http://127.0.0.1:${API_PORT}/healthz" >/dev/null 2>&1; then HEALTHY=1; break; fi
  printf '.'; sleep 1
done
printf '\n'
[ "$HEALTHY" -eq 1 ] || {
  warn "the agent has not answered on the info port yet — showing recent logs:"
  docker logs --tail 40 zagros-node 2>/dev/null || true
  die "node did not become healthy (see the logs above; try: zagros-node logs)"
}
ok "agent is listening on :$PORT (control plane) and :$API_PORT (info)"

# --------------------------------------------------------------------------- #
step "Pairing material — copy this into the panel"
# --------------------------------------------------------------------------- #
"$CLI_PATH" info 2>/dev/null || warn "could not read node info (is the container running?)"

cat <<EOF

${B}Next step in the panel${N}
  Nodes → the node you created → ${C}set manual${N} (or press ${C}connect${N}), then confirm the
  fingerprint printed above. The panel pins the certificate and completes the
  pairing with the one-time token.

${D}Useful commands${N}
  ${D}#${N} zagros-node status      — lifecycle state of every core on this node
  ${D}#${N} zagros-node logs -f      — agent log stream
  ${D}#${N} zagros-node cert         — the pinned SHA-256 fingerprint again
  ${D}#${N} zagros-node update       — pull the current image and restart
  ${D}#${N} zagros-node uninstall    — remove the node (--purge also deletes data)

EOF

if [ -n "$PANEL_ID" ]; then
  info "panel id: $PANEL_ID"
fi
if [ -z "$TOKEN_HASH" ]; then
  warn "no --token was given: the panel cannot claim this node until you run"
  warn "  zagros-node reset-registration <sha256-of-a-new-token>"
fi
